### PR TITLE
TurtleShroom Productions VI

### PR DESCRIPTION
**Pull request by TurtleShroom**
HERE I GO AGAIN ON MY OWN! GOING DOWN THE ONLY ROAD I'VE EVER KNOWN!

### CODE REVIEW

**Comment by loup99** [comment]
Was the opening post supposed to be a criticism? In that case I'd appreciate if you could provide more details so that we can sort it out.

Another thing I'd like tro comment is that I'd prefer if you refrained from renaming and shuffling around files, it makes it very difficult to track changes and causes a lot of bugs.

**Comment by TurtleShroom** [comment]
No no, it wasn't an insult or criticism! We had been discussing the Anarchy bug for a while. I finally fixed it.

**Comment by loup99** [comment]
I think there are issues on multiple levels with what you did with the HRE. Long story short however: it's not getting into the mod and it is vanilla code included for maintenance purposes (not meant to be modified). And it's not open to discussion, as we already settled on the matter (we are going to do something different).

Then the functional placeholder "Anarchy" government for Bureaucratic governments will remain until there is an artist. The placeholder image you used won't be included.

I don't want you to move around any files. It can be done in two clicks, and it's an incredible hassle if you do it. Suggest instead with words, and I will do it directly. 

On flags, we can't use any extended timeline flags.

**Comment by TurtleShroom** [comment]
Why in the heck do you want the Anarchy thing when I have a TEMPORARY solution? I'm not asking for my picture to bepermanent. I'm just sick of seeing a man getting decapitated and calling me an anarchy. That mistake has been here for years and it's high time you got around to fixing it.

I tried to set it so that you could restore the HRE if the WRE falls. I don't see why you don't just erase the daggum thing if you don't use it. However, I will gladly remove it.

Now, about testing.

I have taught myself how to validate my code. I now test EVERYTHING I implement. There is absolutely no need to worry abut that. I validate all code by hand!

**Comment by loup99** [comment]
- First of all, the "Anarchy" name is not a bug, not more than the name "Smith" for dynasty. It is just the vanilla default when there is nothing else. Secondly, we need to find an artist. Until that has been found it is better to either use "Anarchy" as a placeholder, or use another existant vanilla picture, but with a new name. It also hasn't been around for years, that addition to the vanilla game is fairly recent. 😉 
- We don't erase it for maintenance/compatibility purposes. It may be recycled later on.
- Could you undo the renaming?
- Great, but why not use the Validator too?

**Comment by TurtleShroom** [comment]
1. You are correct, it hasn't been around for years and I am mistaken. My apologies. I still think we should just stick with the picture I'm using until we get a real artist. I'm really proud of my attempt, and it's not going to last longer. I actually know an artist that may be able to produce a proper picture.

2. Understood. I'll just put pound signs on the Potential section and leave it as-is.

3. It's not Pagan Religious Heads. It's Religious Heads. That stays.

4. I still struggle with the Validator and I can't download the newest version. I prefer my manual testing, anyway.

**Comment by loup99** [comment]
- I will look at the picture to see what we can do
- Good
- We are not in disagreement over that there could be a name change: I just want to save you time and conflicts by doing it directly on the main branch.
- I'm not opposed to manual validation or using the logs (which you should do too), but as you can use the Validator if you put the proper path I don't see why you wouldn't use that too

**Comment by loup99** [comment]
- Please don't use triggered modifiers, they are incredibly performance costly. We should remove all of them.

**Comment by TurtleShroom** [comment]
What performance cost? I have never seen anything remotely detrimental. Do you have an alternate to triggered modifiers?

**Comment by loup99** [comment]
I'm not going to go into the details given that it is explained in the official optimisation thread. Yes, event modifiers.

**Comment by loup99** [comment]
In order to solve the dilemma of the massive workoad I have decided the following: Each commit will have to be a separate issue,to avoid pull requests.

**Comment by TurtleShroom** [comment]
@loup99 

Ah crap, I did something wrong, didn't I? Am I pushing Commitments too fast?

-----------------

Also, how do I use Event Modifiers? I don't understand how to create those or what to do with them. My guess is that I write Events instead of Triggered Modifiers and use the same code, but I don't know what that means.

What are Event Modifiers and where can I find them? Are they written differently from Triggered Modifiers? Would I apply them the same way I cause Traits to appear and disappear based on code?

**Comment by loup99** [comment]
You are not pushing anything too fast, and I'm the one who did things wrong. I would however like if we could use issues rather than pull requests. For each thing you want to change, you can open a new issue. I think that is a more efficient way of working.

On event modifiers, I'm not going to pretend that I'm better than the wiki at explaining, because I'm not, so here you go: http://www.ckiiwiki.com/Modifiers#Event_modifiers

**Comment by loup99** [comment]
Also, we didn't discuss your new heresy, but with the new DLC I can safely say that it will be for a sub-mod. At least until the DLC is released.

**Comment by TurtleShroom** [comment]
The new EP seems to allow the player to join SECRET cults and SECRET Gnostic orders.

That does not fit in the Mod's time period. In this time, OPEN Gnosticism existed. Therefore, the religious addition that I spent over eight hours on should stay.

WHEN the new EP is released, we will asjust to it accordingly.

Don't leave me in the cold. Let us cross that bridge when we find it.

**Comment by loup99** [comment]
No, open Gnostic heresies.

**Comment by TurtleShroom** [comment]
I can't and won't do the Issues suggestion. I use Pull Requests because it allows for dynamic and rapid revisiins abd edits. If I made one issue per edit or improvement, you would be clogged with hundreds of Issues. That is absolutely ridiculous.

I want to write the code, not ask you to write it for me. Pull Requests ultimately get implemented.

We should still implement my Borborites additions. As I said, we'll cross thatbridge when we find it.

**Comment by loup99** [comment]
I'm not asking you to stop making edits: I want the edits to be suggested beforehand, so that we can save time.

**Comment by TurtleShroom** [comment]
Well folks, I've absolutely destroyed this line by a serious mistake I cannot undo. I will now be closing this Request and reopening Version VII in order to fix this out.

**Comment by TurtleShroom** [comment]
Please don't delete this. I broke everything when I updated from the Master, and now I can't get it back. I had to delete everything to even access it. This is all I have left from the days of work I did implementing several useful features.

**Comment by loup99** [comment]
Even if I would like to delete it, I wouldn't be able to do it. However as the repository has been deleted, I can't reopen or merge this with master.

**Comment by loup99** [comment]
Given that much of the content of this branch has either been discussed in other contexts, not been reviewed at all or is in conflict with the main branch, I don't feel confident in including it's content to the main branch, especially as we aim to release a bug-fixing version soon. However the Sethian religious head addition and Adoptionism head fix have both been added to the main branch.

**Comment by MaelgwnGwynedd** [comment]
This pull system doesn't seem to work very well.

**Comment by loup99** [comment]
Two things haven't been done well, both due to my fault:

- Communication with Turtleshroom as he has been adding a lot of things before discussing them, making it into lost work if thereis disagreement or misunderstanding
- Explaining how the Pull Requests work and how merges are to be done.

**Comment by MaelgwnGwynedd** [comment]
There's also the issue of you having to check every single addition.

**Comment by loup99** [comment]
I see that as an advantage (also it's not just me who can check them), as it allows for finding bugs and discussing eventual issues.

**Comment by MaelgwnGwynedd** [comment]
But why should you be the one to do it?

**Comment by loup99** [comment]
Discussing and searching for bugs? I don't get why you ask that, it is natural that everyone in the dev team participates in those discussions.

**Comment by MaelgwnGwynedd** [comment]
But it's only you when reviewing these.

**Comment by loup99** [comment]
That may be because I'm the only one having time, because others are not following GitHub, or because others focus on other matters. But there is no decision that I "should" be doing anything.

**Pull request closed without merging**
