### PR TITLE
Roman victory titles

### PR DESCRIPTION
**Pull request by rquinio**
Adding [Roman victory titles](https://en.wikipedia.org/wiki/Victory_title#Roman_victory_titles), as nicknames for Roman culture generals, based on:

- the culture of the vanquished: 'Gothicus' = Victorious over the Goths
- the geographical region of the battle: 'Africanus' = Victorious in Africa

When titles overlap between both, the first is preferred.
Please review the changes !

### CODE REVIEW

**Comment by rquinio** [comment]
I also checked for adding latin [Agnomen](https://en.wikipedia.org/wiki/Agnomen) for nicknames ('the Fat' => 'Crassus'), but cultural localization for nicknames doesn't work, so it would be lot of work to duplicate the nicknames.

**Comment by loup99** [comment]
Nice! Looks good.

**Comment by rquinio** [comment]
No, I think it was never implemented (i.e. nick_the_fat_roman;Crassus;;;;x)
There was an update to use localization commands (ex: [Root.Culture.GetName] inside a nickname (the 'Roman'), but it's very limited...

**Comment by loup99** [comment]
Oh, OK, I must have misunderstood it at the time then. 

Merging this.

**Pull request merged**
