### PR TITLE
Better Imperial Regalia icons

### PR DESCRIPTION
**Pull request by IhateTrains**
I added a lance and a crown.  #250

### CODE REVIEW

**Comment by loup99** [comment]
Here are some crown pictures:

image

image

**Comment by IhateTrains** [comment]
I will replace it in the future.

**Comment by loup99** [comment]
Just a few things I noted:
This should be inside an ACR file:
`first_academy_restored;First Academy restored;Premi�re acad�mie restor�e;;;;;;;;;;;;x`

These should be separate, I don't know where they are from:
```
bogomilism_spreading;Bogomilism spreading;Propagation du Bogomilism;;;;;;;;;;;;x
bogomilism_formalized;Bogomilism formalized;Formalisation du Bogomilism;;;;;;;;;;;;x
bogomilism_organized;Bogomilism organized;Organisation du Bogomilism;;;;;;;;;;;;x
bogomil_appears;Bogomil appears;Apparition du Bogomilism;;;;;;;;;;;;x
```

**Comment by IhateTrains** [comment]
done

**Comment by IhateTrains** [comment]
I fixed "Ambition graphic for "Go Travelling" displaying oddly"

**Comment by loup99** [comment]
I think what is causing all of these commits to be a part of this pull request is that you are asking for a merge from the full IhateTrains:master into loup99:master rather than of a branch on IhateTrains into loup99:master.

**Comment by loup99** [comment]
Is it time for a merge? I read your note in the Google Sheet.

**Comment by IhateTrains** [comment]
Yes, it can be merged.

**Pull request merged**
