### PR TITLE
Root west pagan

### PR DESCRIPTION
**Pull request by rquinio**
This is linked to https://github.com/loup99/WtWSMS/issues/132
@TurtleShroom @loup99 Feel free to review ;)
Once OK, I'll solve the merge conflicts and merge the PR.

### CODE REVIEW

**Comment by loup99** [comment]
I know nothing about this religion, but it looks good codewise!

**Comment by TurtleShroom** [comment]
I'll review it right now. I've got CK2 right here, and I'll create a Root West character in the Ruler Designer and see if the changes work.

**Comment by TurtleShroom** [comment]
Okay, you missed one thing I addded:

YO_BLACKHEAD;Majestic Intercessor;;;;;;;;;;x,,

This was the FOA of the head of Reformed Root West, the Black Intercessor.

**Comment by TurtleShroom** [comment]
I also uploaded the COA for the Holy Order and the religious head in the original Issue file.

**Comment by TurtleShroom** [comment]
if you were waiting on my permission to put it in, go ahead; you guys can go ahead and install this into the game.

**Comment by rquinio** [comment]
Still a few things missing (holy order creation event + your localization feedback).

**Comment by rquinio** [comment]
I've fixed the remaining issues and adjusted a bit some localizations after testing, ready to merge.

**Pull request merged**
