### PR TITLE
Gubernatorial Elective

### PR DESCRIPTION
**Pull request by IhateTrains**
Added a new succession type for Bureaucratic governors: Gubernatorial Elective
- The next governor is elected by influential people in the realm, with the top liege's vote having a huge weight
- The Roman provinces are no longer hereditary
- A human player being the top liege can use a decision to toggle his vote in a particular title off or on

Some screenshots:
image
image
image
image

### CODE REVIEW

**Comment by loup99** [comment]
Nice work, I'm going to test it more in detail before reviewing! 👍

**Comment by IhateTrains** [comment]
ad. 1 I have two ideas: "Provincial Elective" and "Gubernatorial".

**Comment by IhateTrains** [comment]
ad. 2 Have you waited a few days for the candidate to change? It's not immediate.

**Comment by IhateTrains** [comment]
Seems I've found an issue. You could only choose from unlanded and non-heir people, and when chosen, the candidate would become the heir to the elective title, making him invalid...

**Comment by IhateTrains** [comment]
@loup99 Both points should be addressed now ✔️.

**Comment by loup99** [comment]
Ok, I will retest and get back to this with further feedback.

**Comment by loup99** [comment]
Ok, I will retest and get back to this with further feedback.

**Comment by loup99** [comment]
The feature is interesting but it does not fully work, if someone else wants to pick this up we can reopen and reconsider.

**Pull request closed without merging**
