### PR TITLE
Reopened PR - updating mod files, tweaking converter

### PR DESCRIPTION
**Pull request by IhateTrains**

### CODE REVIEW

**Comment by loup99** [comment]
Tell me when you are done with this, and I will add it. What exists in the branch currently was sent to me by an user to help out, and I haven't personally altered it.

**Comment by IhateTrains** [comment]
It depends on progress of Operation Ptolemy: if you're going to change the map for the next release, you can merge this PR. If the map stays as it is, I will map the missing provinces to make the converter ready for release.

**Comment by loup99** [comment]
Operation Ptolemy is not getting added in the next release.

**Comment by IhateTrains** [comment]
On second thoughts, you should merge it anyway. If someone decides to help to with the converter, he should work with these tweaks included.

**Pull request merged**
