### PR TITLE
PR before JD integration

### PR DESCRIPTION
**Pull request by IhateTrains**
I just want all the minor changes from IhT to be merged into master before we start integrating patch 2.8

The only major change is Samaritan High Priest list

### CODE REVIEW

**Comment by loup99** [comment]
Other than the file being called "mizrahim" rather confusingly, I don't have anything to add. 👍

**Comment by IhateTrains** [comment]
OK, moved to hebrew.txt

**Comment by loup99** [comment]
Also while I'm at it, could you just update the changelog too? Thanks a lot!

**Comment by IhateTrains** [comment]
I expanded the existing line

**Pull request merged**
