### PR TITLE
 🎶 Imperial Fleet rule the waves 🎶

### PR DESCRIPTION
**Pull request by IhateTrains**
- Imperial Fleet for ERE and WRE
- Khosrau I trait additions based upon the forum suggestion
- Validator fixes

### CODE REVIEW

**Comment by IhateTrains** [comment]
What do we do with the Fleets?

**Comment by loup99** [comment]
As I said, I can adapt them to the legions system.

**Comment by IhateTrains** [comment]
OK, but please don't add holding Constantinople as a condition for now, and we will see how it works out

**Comment by IhateTrains** [comment]
We can use holding the imperial title as a condition for now

**Comment by loup99** [comment]
Not Constantinople, the duchy of Europa was the idea.

**Comment by IhateTrains** [comment]
It's even worse IMO, because even losing an unimportant barony will make the navy disband :/

**Comment by loup99** [comment]
No, sorry, but that is completely wrong. No title disbands because you loose a barony, that condition is only for the formation. 😉

**Comment by IhateTrains** [comment]
It's fine for the creation, I thought you were talking about conditions for existing

**Comment by loup99** [comment]
No, that was not what I meant. Sorry if I was unclear on the matter. What would lead to it disbanding would  basically be if the entire duchy was destroyed if there is no culture condition as you asked.

**Comment by IhateTrains** [comment]
Duchy destroyed as a title or area?

**Comment by loup99** [comment]
Do you know what? I will do the change, and then it will hopefully be more clear so that we can't discuss on that basis instead.

**Comment by IhateTrains** [comment]
- The fleet disbands when the duchy title is destroyed, even when no land is lost
- The fleet commander is still feudal, is it intended?

**Comment by IhateTrains** [comment]
Once again I disagree with the disbanding conditions:
- Flaminia wasn't very imporant for the western fleet, there were many big ports elsewhere
- d_europa and d_flaminia were supposed to be in creation decision conditions

**Comment by IhateTrains** [comment]
I have set a better event picture.

**Comment by loup99** [comment]
No, not intended, oversight by me.

**Comment by loup99** [comment]
> Flaminia wasn't very imporant for the western fleet, there were many big ports elsewhere

The fleet was based upon that port to my knowledge, making it pretty essential. What other big ports are you referring to? Furthermore, I don't see the need for railroading into specific ports. There is one key location, then the player picks the others.

> d_europa and d_flaminia were supposed to be in creation decision conditions

They are, as I said. I already explained this to you:
> What would lead to it disbanding would basically be if the entire duchy was destroyed if there is no culture condition as you asked.

**Comment by IhateTrains** [comment]
According to Wikipedia: Major Roman ports were:
Portus Julius, located at Misenum
Classis, near Ravenna
Alexandria
Leptis Magna
Ostia
Portus
Port of Mainz (Mogontiacum, river navy on the Rhine)

The fleet shouldn't autodisband when the "one key location is lost" (now it doesn't even have to be lost, they disband when you destroy the duchy title), but move to other key locations.

> Furthermore, I don't see the need for railroading into specific ports. There is one key location, then the player picks the others.

But even if you i.e. move capital and your entire demesne to Roma and surroundings (with some great ports), you still need to control d_flaminia :/

**Comment by IhateTrains** [comment]
I suggest being a vassal of the Empire and the Empire having a coastal province as conditions for existing

**Comment by IhateTrains** [comment]
Maybe we should ask the community about their preferences?

**Comment by loup99** [comment]
Merged the triple post. 

> According to Wikipedia: Major Roman ports were:
> Portus Julius, located at Misenum
> Classis, near Ravenna
> Alexandria
> Leptis Magna
> Ostia
> Portus
> Port of Mainz (Mogontiacum, river navy on the Rhine)
> 
Ports for trade yes. Does that mean the imperial navy was based around there? No. And here you are mixing things up completely, because these are from both the West and East, Mediterranean and other seas, so it doesn't pertain to my question at all. 

> The fleet shouldn't autodisband when the "one key location is lost" (now it doesn't even have to be lost, they disband when you destroy the duchy title), but move to other key locations.
>
Agreed, good that it doesn't autodisband then, as you observe. However, moving to other key locations, when those didn't exist and the titles have a specific port of attachment is neither plausible nor interesting, especially if we are to mix trade ports and naval bases. 

> But even if you i.e. move capital and your entire demesne to Roma and surroundings (with some great ports), you still need to control d_flaminia :/

No, the duchy just has to not be disbanded. Which the AI never does, as a reminder. 

> I suggest being a vassal of the Empire and the Empire having a coastal province as conditions for existing

That is not how it worked historically though, did it? You are just mentioning the conditions for having vassal levies, which you confuse with the special mercenary unit.

> Maybe we should ask the community about their preferences?

If there was a serious disagreement that could have been an alternative, but given that we are not even discussing the same things I don't know what it would serve but to confuse.

I invite you to continue the discussion in the forum group if you find this page to be difficult to use. Would also allow for other devs to provide input, once the misunderstandings have been cleared up.

**Comment by IhateTrains** [comment]
OK, created a thread in the group

**Comment by loup99** [comment]
Yeah, but new thread are buggy because after other threads disappear and you don't get notifications, so I prefer posting in the main thread.

**Pull request merged**
