### PR TITLE
Add 24 new legions

### PR DESCRIPTION
**Pull request by khagler**
These are the legions shown on the map in the forum (https://forum.paradoxplaza.com/forum/index.php?threads/list-of-createble-legions-and-their-attached-provinces.889354/#post-22075320) that weren’t yet in the mod. I understand the map is a work in progress, but should a legion’s home duchy move it’s a one line change to WtWSMS_organise_legions_decisions.txt and WtWSMS_legion_events.txt to update it.

### CODE REVIEW

**Comment by loup99** [comment]
Great work! I have two comments on this:

1. The GitHub repository being of a private nature and only destined for modders and testers, we store our credits on the forum page, not here, since this area is not meant for any external contributor. 
2. You made all the new legions active. The intent is for none of these new ones to be that at start, to my knowledge.

**Comment by khagler** [comment]
Fixed.

**Comment by loup99** [comment]
Thanks for the quick response! I noted another thing, you removed the commented out entries in the decisions file. While I don't think those entries will come back any time soon, we would prefer to keep them in case they do

**Comment by loup99** [comment]
Don't worry about too much about bad practice when you commit anything here @khagler.  The WtWSMS mod is filled with such bad practice for legacy reasons. That said, I understand the point, in the future we might review this.

**Pull request merged**
