### PR TITLE
TurtleShroom Productions Branch

### PR DESCRIPTION
**Pull request by TurtleShroom**

### CODE REVIEW

**Comment by TurtleShroom** [comment]
Okay, so how do I test these changes out? Do I just copy and paste the changed items into the Mod folder and hope it works?

**Comment by loup99** [comment]
On what did you do these edits? With GitHub for Windows, I presume? If yes, then you only need to be on that branch and the changes are automatically there. Then you need to remove the old mod files and link the folders in the GitHub folder with the mod one. See the README.md

**Comment by TurtleShroom** [comment]
The MS-DOS Batch file says that it can't find the file specified, despite getting the path address correct.

wrong

**Comment by TurtleShroom** [comment]
It seems I am struggling with modding Autocephalacy into the Mimamsa religion. Its five Pentarchies aren't the proper Mimamsa Holy Sites.

The post is here. I'd reccomend answering anything there, so other people can read it to mod Autocephalacy.
https://forum.paradoxplaza.com/forum/index.php?threads/how-to-mod-autocephalacy.935788/

**Comment by TurtleShroom** [comment]
I can't fix the localization. If anyone else wants to take a look at it, be my guest. I give up.

**Comment by TurtleShroom** [comment]
@loup99 

I can't fix the localization. If anyone else wants to take a look at it, be my guest. I give up. The code works, though.

**Comment by TurtleShroom** [comment]
The change log says I keep adding commas to everything. When I check the files, there are no commas. Ignore any commas you see.

**Comment by loup99** [comment]
- I don't know where you have located all files if they are not in the default folders.
- Pentarchy/autocephaly isn't completely moddable at this point
- If you have issues and is frustrated, I recommend that you take a step back and do something else for a while. Leave the modding, and come back if you feel like trying again, with a new perspective.

**Comment by TurtleShroom** [comment]
@loup99 

It's getting worse. For some reason, now, the "I've Been Appointed as Your Regent" message has two options and they give you the modifiers from my Patrons Decision.

I think I'm going to scrap the entire Patrons Event system, because I'm too stupid to know how to write any Events, and just make it two decisions.

**Comment by TurtleShroom** [comment]
Okay, so I humiliated myself because I am too stupid to write Events. I'm going to delete the entire thing and start over with the newest version.

**Comment by loup99** [comment]
OK, in that case I will close this.

**Pull request closed without merging**
