### PR TITLE
Roman Empire Restoration

### PR DESCRIPTION
**Pull request by loup99**
Worked on some roman stuff:
- WRE can now restore and interact with a potentially restored empire
- If one ruler holds both empire titles they can unite them
- If one of the empires fall, the other one can get acess to the full CB
- As the Roman Empire you have acess to the same full CB

It is WIP and needs polishing/testing

### CODE REVIEW

**Comment by EWattman** [comment]
Does the United Empire have a requirement of having both titles to be restored?

**Comment by loup99** [comment]
The united empire has as requirement that the holder holds both titles.

**Comment by rquinio** [comment]
Cool ! I'll review this :)

**Comment by loup99** [comment]
Now most of what did not work should be fixed, although I still have some issues/questions:
- Restoring/Unifying Rome does not destroy the empire titles, not sure why
- The decision about being the "sole" roman empire left does not appear, I will have to look into the potential
- Where can I find the the GFX icon for the LoR decicions to reuse them?

**Pull request merged**
