### PR TITLE
Made c_at_ta_if actually include Ta'if

### PR DESCRIPTION
**Pull request by IhateTrains**
- removed duplicate b_taif
- moved b_qunfudhah and b_turubah to c_at_ta_if (b_qunfudhah because it's far beyond the province of Mecca on map and b_turubah because it's closer to Ta'if than Mecca)

Map comparison:
adnotacja1
adnotacja2

This fixes "Barony of Ta'if (b_taif) in Mecca province and County of At Ta'if (c_at_ta_if) duplicate"

### CODE REVIEW

**Comment by IhateTrains** [comment]
I checked and it's not possible if we want to keep the Banu Thaqif (which holds c_at_ta_if) on the map.

**Comment by loup99** [comment]
They inhabit the Ta'if area, which corresponds anyway, no?

**Comment by loup99** [comment]
The region is a wider area than the city itself today. We don't have the same outlook on this problem, since I don't believe all neighbouring provinces have to change as the opening post suggests. 

39940542-e3cbee46-5559-11e8-8758-1c997962beed

**Comment by IhateTrains** [comment]
What is the "Ta'if region"? 
> "In the 6th century the city of Tā'if was dominated by the Banu Thaqif tribe, which still lives in and around the city of Taif today.

It is clear that they held the city itself, so the current area of Tā'if province in master branch is wrong.

I gave a part of c_mecca province to c_bard province for better province shapes, but I can revert it.

**Pull request merged**
