### PR TITLE
Made Julius Nepos bureaucratic at start

### PR DESCRIPTION
**Pull request by IhateTrains**
As suggested by starwarsfan541
https://forum.paradoxplaza.com/forum/index.php?threads/wtwsms-suggestions-ideas.827029/page-45#post-22397569

### CODE REVIEW

**Comment by IhateTrains** [comment]
See 0c53a71

**Comment by loup99** [comment]
Still problematic, because you can start in a bookmark in say 476, and then Nepos falls but another character (like the tribal Gepids) then reform the title and get the Bureaucratic government.

**Comment by IhateTrains** [comment]
Would adding has_romance_culture_trigger = yes to the AND clause be enough?

**Comment by loup99** [comment]
I don't think Dalmatia should give a Romance ruler the Bureaucratic government for free. What do you think?

**Comment by IhateTrains** [comment]
I could add `holder = { has_claim = e_wre }`

**Comment by loup99** [comment]
I still find it problematic since that would imply another claimant getting the government type. My preferred course of action would therefore be a flag set in title history, which would be removed when Nepos gets the WRE or if Nepos dies without a heir.

**Comment by IhateTrains** [comment]
See 9f31e09
I wanted to use a title flag but didn't manage to get it to work 🤔 Global flag works well, fortunately.

**Comment by loup99** [comment]
According to the file it should be Bureaucratic from 454 and onwards, actually.

**Comment by IhateTrains** [comment]
Should be done now.

**Pull request merged**
