### PR TITLE
North Africa Map Tweaks

### PR DESCRIPTION
**Pull request by loup99**
A pull request/branch for the work around the province layout in Northern Africa. Thanks to Moopli for contributing with a province.bmp.

NOTE: I'm just commiting this now, but my personal priority will be on the 2.5.x compatibility until the next WtWSMS version is released, of course.

### CODE REVIEW

**Comment by rquinio** [comment]
Does that version of province.bmp include the recent changes due to eastern expansion (colors in Africa had to be shifted) merged with the changes from IratePirate (7ab1bda8bba256bce13ff168d5283cfd0825c273) ?

**Comment by loup99** [comment]
No, it does not, which is why I did not directly push it.

**Comment by rquinio** [comment]
I checked, will be very difficult to merge, probably best to restart from scratch on current version.
Is there a list of removed / new / renamed provinces ? Additional history for the new titles will be needed ?

**Comment by loup99** [comment]
OK, but this doesn't really add any new titles/remove provinces, it just moves around those in Northern Africa, so it should be possible to restart from scartch quite easily

**Comment by loup99** [comment]
I have removed the files and fixed the colour issues, but it still crashes... Any idea of what might be causing it?

**Comment by rquinio** [comment]
The branch was not compatible with 2.5, I did a merge from master to solve the crash, now it loads fine.
I'll let you continue the map changes, I've noticed a color conflict for 1 province in the Sahara with the steppes.

**Comment by loup99** [comment]
Oh, I had forgotten that. Thank you!

**Comment by tannerflick4** [comment]
What is needed to get this pull request/branch to be merged?

**Comment by loup99** [comment]
It won't be. This is no longer of actuality, and we rather await Operation Ptolemy.

**Comment by loup99** [comment]
With the merge of #431 this pull request is obsolete.

**Pull request closed without merging**
