### PR TITLE
added some decision icons + six secret societies files finished

### PR DESCRIPTION
**Pull request by IhateTrains**
- call_synod_of_whitby
- lex_burgundionum
- twothousandth_anniversary_gothic_kingdom
- hold_akelarre
- sacrifice_black_goat
- erect_megalith
- create_binitarian_patriarchy
- create_ebionites_patriarchy
- create_apollinarian_patriarchy
- create_adoptionian_patriarchy
- create_patripassian_patriarchy
- restore_bishop_of_carthage
- create_valentinian_patriarchy
- create_sethian_patriarchy
- create_bishop_of_iona
- create_pelagian_bishop
- recruit_donatist_bands

### CODE REVIEW

**Comment by IhateTrains** [comment]
I've got a new loadingscreen proposal: https://1drv.ms/u/s!AkkXLHHhb2v-haBFvW-gysZ8C8C3AQ

**Comment by loup99** [comment]
I prefer 1 for 10. As for 12, could it be a bit less blurry?

**Comment by IhateTrains** [comment]
sure

**Comment by loup99** [comment]
Good!

**Comment by IhateTrains** [comment]
I think it's ready to be mergeg, the societies lack localisation but it doesn't affect stability.

**Comment by loup99** [comment]
Is it still ready, or did you decide to continue working on it?

**Comment by IhateTrains** [comment]
it should be merged, localisation can wait

**Comment by IhateTrains** [comment]
There's one part of the eighth societies file that may be unfinished

> option = {
		name = EVTOPTA_MNM_3820
		
		trigger_switch = {
			on_trigger = has_character_flag
			
			### WtWSMS ###        many religions are lacking here, should I add them?
			sr_aquileian_prov_flip = { 
				any_demesne_province = {
					limit = {
						has_province_modifier = secret_aquileian_community
					}
					religion = aquileian
					remove_province_modifier = secret_aquileian_community
				}
			}
			sr_nicene_prov_flip = { 
				any_demesne_province = {
					limit = {
						has_province_modifier = secret_nicene_community
					}
					religion = nicene
					remove_province_modifier = secret_nicene_community
				}
			}
			sr_total_depravity_prov_flip = { 
				any_demesne_province = {
					limit = {
						has_province_modifier = secret_total_depravity_community
					}
					religion = total_depravity
					remove_province_modifier = secret_total_depravity_community
				}
			}
			sr_eutychian_prov_flip = { 
				any_demesne_province = {
					limit = {
						has_province_modifier = secret_eutychian_community
					}
					religion = eutychian
					remove_province_modifier = secret_eutychian_community
				}
			}
			sr_binitarian_prov_flip = { 
				any_demesne_province = {
					limit = {
						has_province_modifier = secret_binitarian_community
					}
					religion = binitarian
					remove_province_modifier = secret_binitarian_community
				}
			}
			sr_georgian_orthodox_prov_flip = { 
				any_demesne_province = {
					limit = {
						has_province_modifier = secret_georgian_orthodox_community
					}
					religion = georgian_orthodox
					remove_province_modifier = secret_georgian_orthodox_community
				}
			}
			sr_insular_prov_flip = { 
				any_demesne_province = {
					limit = {
						has_province_modifier = secret_insular_community
					}
					religion = insular
					remove_province_modifier = secret_insular_community
				}
			}
			sr_pelagianism_prov_flip = { 
				any_demesne_province = {
					limit = {
						has_province_modifier = secret_pelagianism_community
					}
					religion = pelagianism
					remove_province_modifier = secret_pelagianism_community
				}
			}
			sr_antinomianism_prov_flip = { 
				any_demesne_province = {
					limit = {
						has_province_modifier = secret_antinomianism_community
					}
					religion = antinomianism
					remove_province_modifier = secret_antinomianism_community
				}
			}
			sr_ebionites_prov_flip = { 
				any_demesne_province = {
					limit = {
						has_province_modifier = secret_ebionites_community
					}
					religion = ebionites
					remove_province_modifier = secret_ebionites_community
				}
			}
			sr_taoism_prov_flip = { 
				any_demesne_province = {
					limit = {
						has_province_modifier = secret_taoism_community
					}
					religion = taoism
					remove_province_modifier = secret_taoism_community
				}
			}
			
Should I put all the missing religions there?

**Comment by IhateTrains** [comment]
I haven't noticed that before because I followed @tannerflick4 's example and he may have forgotten about this part.

**Comment by loup99** [comment]
Yes. @tannerflick4 did fill in that in his societies.

**Comment by tannerflick4** [comment]
I'm still working on these too. I was actually in the process of adding each religion in each section instead of going 1 by 1.

**Comment by IhateTrains** [comment]
Shall I leave it to you? I could get back to the converter.

**Comment by tannerflick4** [comment]
Yeah that would be cool. I'm limited in what work I know how to do so no one else should spend time on something this simple lol :)

I'm on vacation so that's why I'm not going as fast as usual.

Tanner

**Comment by tannerflick4** [comment]
oh my! you did a ton of them. wow. which files did you not work with?

when I first read this, I thought you had just only touched 6 secret religions and just added their code through all the files.

Sorry, I am just a bit protective of work that I have been given that is easy and I have started on.

**Comment by IhateTrains** [comment]
There's a part of eighth file (mnm_secret_religious_societies_events.txt) that hasn't been filled with all religions, I will post this fragment here. Many religions lack localisation.

**Comment by IhateTrains** [comment]
> option = {
		name = EVTOPTA_MNM_3820
		
		trigger_switch = {
			on_trigger = has_character_flag
			
			### WtWSMS ###        many religions are lacking here, should I add them?
			sr_aquileian_prov_flip = { 
				any_demesne_province = {
					limit = {
						has_province_modifier = secret_aquileian_community
					}
					religion = aquileian
					remove_province_modifier = secret_aquileian_community
				}
			}
			sr_nicene_prov_flip = { 
				any_demesne_province = {
					limit = {
						has_province_modifier = secret_nicene_community
					}
					religion = nicene
					remove_province_modifier = secret_nicene_community
				}
			}
			sr_total_depravity_prov_flip = { 
				any_demesne_province = {
					limit = {
						has_province_modifier = secret_total_depravity_community
					}
					religion = total_depravity
					remove_province_modifier = secret_total_depravity_community
				}
			}
			sr_eutychian_prov_flip = { 
				any_demesne_province = {
					limit = {
						has_province_modifier = secret_eutychian_community
					}
					religion = eutychian
					remove_province_modifier = secret_eutychian_community
				}
			}
			sr_binitarian_prov_flip = { 
				any_demesne_province = {
					limit = {
						has_province_modifier = secret_binitarian_community
					}
					religion = binitarian
					remove_province_modifier = secret_binitarian_community
				}
			}
			sr_georgian_orthodox_prov_flip = { 
				any_demesne_province = {
					limit = {
						has_province_modifier = secret_georgian_orthodox_community
					}
					religion = georgian_orthodox
					remove_province_modifier = secret_georgian_orthodox_community
				}
			}
			sr_insular_prov_flip = { 
				any_demesne_province = {
					limit = {
						has_province_modifier = secret_insular_community
					}
					religion = insular
					remove_province_modifier = secret_insular_community
				}
			}
			sr_pelagianism_prov_flip = { 
				any_demesne_province = {
					limit = {
						has_province_modifier = secret_pelagianism_community
					}
					religion = pelagianism
					remove_province_modifier = secret_pelagianism_community
				}
			}
			sr_antinomianism_prov_flip = { 
				any_demesne_province = {
					limit = {
						has_province_modifier = secret_antinomianism_community
					}
					religion = antinomianism
					remove_province_modifier = secret_antinomianism_community
				}
			}
			sr_ebionites_prov_flip = { 
				any_demesne_province = {
					limit = {
						has_province_modifier = secret_ebionites_community
					}
					religion = ebionites
					remove_province_modifier = secret_ebionites_community
				}
			}
			sr_taoism_prov_flip = { 
				any_demesne_province = {
					limit = {
						has_province_modifier = secret_taoism_community
					}
					religion = taoism
					remove_province_modifier = secret_taoism_community
				}
			}

**Comment by IhateTrains** [comment]
about line 8100

**Comment by tannerflick4** [comment]
Thats it? Just this part posted above and localizations?

**Comment by IhateTrains** [comment]
There's a fragment near line 2800 in eighth file where religions are divided into groups. You can check if I divided them properly.

> desc = {
>         trigger = {
>             OR = {
>                 religion = catholic
>                 religion = cathar
>                 religion = fraticelli
>                 religion = waldensian
>                 religion = lollard
>                 religion = nestorian
>                 religion = messalian
> 				religion = aquileian
> 				religion = nicene
> 				religion = total_depravity
> 				religion = eutychian
> 				religion = binitarian
> 				religion = georgian_orthodox
> 				religion = insular
> 				religion = pelagianism
> 				religion = antinomianism
> 				religion = ebionites
> 				religion = marcionism
> 				religion = montanist
> 				religion = sethian
> 				religion = valentinianism
> 				religion = apollinarian
> 				religion = adoptionism
> 				religion = docetic
> 				religion = pneumatomachians
> 				religion = melchisedechianism
> 				religion = patripassianism
> 				religion = sabellianism
> 				religion = psilanthropism
> 				religion = audianistic
> 				religion = arian
> 				religion = monarchianism
> 				religion = donatism
> 				religion = priscillianism
>             }
>         }
>         text = EVTDESC_MNM_3225_A
>     }
>     desc = {
>         trigger = {
>             OR = {
>                 religion = orthodox
>                 religion = bogomilist             
>                 religion = monothelite
>                 religion = iconoclast
>                 religion = paulician
>                 religion = miaphysite
>                 religion = monophysite
>             }
>         }
>         text = EVTDESC_MNM_3225_A
>     }
>     desc = {
>         trigger = {
> 			OR = {
> 				religion_group = jewish_group
> 				religion = bosporan_faith
> 			}
> 		}
>         text = EVTDESC_MNM_3225_A
>     }
>     desc = {
>         trigger = {
>             OR = {
>                 religion = sunni
>                 religion = zikri
>                 religion = yazidi
>                 religion = ibadi
>                 religion = kharijite
>                 religion = islamic
>                 religion = abadites
>                 religion = quranism
>                 religion = qadariyya
>                 religion = khawariji
>                 religion = haruriyyah
>                 religion = wahhabi
>                 religion = mahdi
>                 religion = salafi
>                 religion = twelver
>                 religion = zayid
>                 religion = ismaili
>                 religion = uwaisi
>             }
>         }
>         text = EVTDESC_MNM_3225_D
>     }
>     desc = {
>         trigger = { religion_group = zoroastrian_group }
>         text = EVTDESC_MNM_3225_E
>     }
>     desc = {
>         trigger = {
>             OR = {
>                 religion = shiite
>                 religion = druze
>                 religion = hurufi
> 				religion = qarmatian
>             }
>         }
>         text = EVTDESC_MNM_3225_D
>     }
>     desc = {
>         trigger = { religion = hindu }
>         text = EVTDESC_MNM_3225_G
>     }
>     desc = {
>         trigger = { 
> 			OR = {
> 				religion = buddhist
> 				religion = confucianism
> 				religion = taoism
> 			}
> 		}
>         text = EVTDESC_MNM_3225_H
>     }
>     desc = {
>         trigger = {
> 			OR = { 
> 				religion = jain
> 				religion = sramanic
> 				religion = bhakti
> 				religion = tantric
> 				religion = mimamsa
> 				religion = carvaka
> 				religion = ajivika
> 			}
> 		}
>         text = EVTDESC_MNM_3225_G
>     }
>     desc = {
>         trigger = {
>             OR = {
>                 religion = norse_pagan_reformed
>                 religion = norse_pagan
>             }
>         }
>         text = EVTDESC_MNM_3225_J
>     }
>     desc = {
>         trigger = {
>             OR = {
>                 religion = baltic_pagan_reformed
>                 religion = baltic_pagan
>             }
>         }
>         text = EVTDESC_MNM_3225_J
>     }
>     desc = {
>         trigger = {
>             OR = {
>                 religion = finnish_pagan_reformed
>                 religion = finnish_pagan
>             }
>         }
>         text = EVTDESC_MNM_3225_J
>     }
>     desc = {
>         trigger = {
>             OR = {
>                 religion = slavic_pagan_reformed
>                 religion = slavic_pagan
>             }
>         }
>         text = EVTDESC_MNM_3225_J
>     }
>     desc = {
>         trigger = {
>             OR = {
>                 religion = tengri_pagan_reformed
>                 religion = tengri_pagan
>             }
>         }
>         text = EVTDESC_MNM_3225_N
>     }
>     desc = {
>         trigger = {
>             OR = {
>                 religion = west_african_pagan_reformed
>                 religion = west_african_pagan
>                 religion = root_west_pagan
>                 religion = root_west_pagan_reformed
>                 religion = sanamahi
>                 religion = sanamahi_reformed
>                 religion = georgian_pagan
>                 religion = illyran_pagan
>                 religion = germanic_pagan
>                 religion = germanic_pagan_reformed
>                 religion = west_pagan
>                 religion = scythian_pagan
>                 religion = scythian_pagan_reformed
>                 religion = semitic_pagan
>                 religion = semitic_pagan_reformed
>                 religion = dravidian_pagan
>                 religion = dravidian_pagan_reformed
>                 religion = central_african_pagan
>                 religion = central_african_pagan_reformed
>                 religion = gurzil_pagan
>                 religion = msoura_pagan
>                 religion = african_solar_pagan
>                 religion = african_solar_pagan_reformed
>                 religion = latin_solar_pagan
>                 religion = latin_solar_pagan_reformed
>                 religion = mandulis_pagan
>                 religion = east_african_pagan
>                 religion = assyrian_pagan
>             }
>         }
>         text = EVTDESC_MNM_3225_O
>     }
>     desc = {
>         trigger = {
>             OR = {
>                 religion = zun_pagan_reformed
>                 religion = zun_pagan
>             }
>         }
>         text = EVTDESC_MNM_3225_P
>     }
>     desc = {
>         trigger = {
>             OR = {
>                 religion = hellenic_pagan
>                 religion = pagan
>                 religion = cybelian_pagan
>                 religion = mastimani
>                 religion = neoplatonist
>                 religion = mithraic_pagan
>             }
>         }
>         text = EVTDESC_MNM_3225_P
>     }
>

**Comment by tannerflick4** [comment]
Ok. I'll get it done.

**Comment by tannerflick4** [comment]
Ok. I think I would rather test for ctds more than do localization, now that I have the last parts of the actual code done (unless @loup99 finds more for me). @IhateTrains , i'll let you keep going with localization.

**Pull request merged**
