### PR TITLE
Map Overhaul: Mesopotamia and western Persia Pt1

### PR DESCRIPTION
**Pull request by Arcvalons**
Added 22 new provinces to Mesopotamia and western Persia. Slightly changed de-jure structure to fit with the new borders, but nothing major (two provinces formerly in d_asuristan I moved to d_media_minor, and a couple others I moved to d_hail. I recommend making d_arabia_magna part of k_oriens, it looks odd as it is right now.

### CODE REVIEW

**Comment by EWattman** [comment]
Could you please revert you color changes? I have a thing going on the forums called "Operation Brush" were I and the community discuss changes to different regions, cultures and such. Just look at my Operation Brush commits and see if they conflict, please?

**Comment by loup99** [comment]
How does this correspond with https://github.com/loup99/WtWSMS/tree/Persia-Map-Changes ?

**Comment by Arcvalons** [comment]
@loup99 Yeah, you can remove that one now, that was an incomplete/wip version of this one.

**Comment by EWattman** [comment]
@loup99 My work spans several commits. The Byzantine changes are in part 4-6, the Persian ones are in part 8-14, the Gallic ones are in "Revert Revert Operation Brush p" and the Dacian ones are in part 20.

**Comment by loup99** [comment]
Not your work, Erik. I intended to ask what commit Arcvalons used as a basis.

**Comment by Arcvalons** [comment]
I branched of the current master and uploaded my changes there. There should be no conflicts there, and as I was testing I recall both Persia and the ERE had the new colors.

**Comment by EWattman** [comment]
Ok good.

**Comment by Arcvalons** [comment]
Actually, I'm seeing in the "Files Changed" tab the colors are different for other titles. I'll check to see if there's something going on there.

**Comment by loup99** [comment]
As well as a holysite

**Comment by Arcvalons** [comment]
Ok, fixed it. Here's some pics:

http://imgur.com/6r2MszU.png

http://imgur.com/bieynLt.png

**Comment by loup99** [comment]
Good, but now the file has the wrong encoding and all cultural localisation is broken.

**Comment by Arcvalons** [comment]
I had copied and pasted the contents of the file rather than uploading it. I think it's fixed now.

**Comment by loup99** [comment]
Looks good. I will merge and we can always edit it more later.

**Comment by Arcvalons** [comment]
Sure, I'll do that.

**Comment by EWattman** [comment]
As both the Second-in-Command and the Mapmaker of the mod, I love how the region looks now. @Arcvalons, would you be interested in doing Eastern Persia?

**Comment by Arcvalons** [comment]
Yeah, I'll do the rest of Persia too. In the east the maps I used actually show very little, so there it'd be more about redrawing current provinces so they look better.

**Comment by EWattman** [comment]
Yeah, but add some too if you can, so that we don't have so many large provinces

**Comment by loup99** [comment]
When appropriate, there should be larger provinces. Don't add too many, it is better to only redraw

**Pull request merged**
