### PR TITLE
Tweaks on bureaucracy government

### PR DESCRIPTION
**Pull request by rquinio**
Here are some tweaks for review:
- Remove dependency of bureaucracy to Charlemagne DLC (vice-royalties are replaced by free duchy revocation if not having Charlemagne DLC). This is to avoid locking mod features behind DLCs.
- Extract bureaucracy to its own file for easier maintenance.
- Move tier check to bureaucracy scripted trigger, as this can cause discrepancies between governments.
- Disable vice_royalty and imperial/feudal administration laws under bureaucracy, to avoid duplication.
- Reverse stability law order, so that minimum is on the left and maximum on the right (like other vanilla laws)
- Simplify bureaucracy government description (was too long and duplicate sentences).

Notes:
- I'm not sure whether retinue bonuses from bureaucracy are actually applied (tooltip in retinue tab doesn't show).
- The +10 demesne limit for the emperor under bureaucracy seems strange to me. Vanilla imperial administration was rather +25 vassal limit.

### CODE REVIEW

**Comment by loup99** [comment]
I must ask though: how could we design bureaucracy so that those with the CM DLC could have acess to viceroyalties instead of duchy revocation?

The bonuses seemed to be in place when they were added (I compared with and without). Then for the reasoning behind the +10, while I separated it I'm not sure about justifications. @Arcvalons might be able to give more details.

**Comment by rquinio** [comment]
I reproduced the bureaucratic -> nomadic switch at some point due to a bug, but this should no longer happen.

I've noticed a little issue: unlanded characters part of emperor's court seem to get bureaucratic government, but it seems hardcoded that granting vice-royalty only works for character with feudal government...

**Comment by loup99** [comment]
OK.

As for the +10, I managed to find @Arcvalons explanation:

> Reading the government threads, having a separate but similar bureaucratic/imperial government for Byzatium, Persia, and Rome seems to be the most sensible option, that way scopes can be applied to each one as necessary. Everything else that remains "Feudal" would eventually be changed to "Post-Roman" or "Sub-Roman". 

>The vanilla Centralization and Viceroyalty Laws would seem to work just fine for these government types, though I'm also making a change to Imperial Administration, which will give more demesne size rather than even more vassals (as that seems to undermine the purpose of the Centralization laws in the first place). For the tax laws, since these characters will be able to hold both castles and cities without penalties, a new "Aristocracy vs Plutocracy" demesne law will determine whether vassals will provide you with levies or tax; you can't expect them to both provide you taxes as a city vassal would and levies as a feudal vassal would, at the same time. I'm looking into increasing retinue size and lowering costs for it, though the mod's Legion system I expect will model standing armies fair enough.

>Finally, I was thinking of coding a Stability system that would replace Crown Authority, things like losing battles and having low prestige would lower it, while winning battles and having high prestige/piety/gold can increase it. Low stability leads to bad things happening, like ambitious generals doing evil stuff to you. That's still very much in the "cool idea" phase though.

**Comment by rquinio** [comment]
Without the +25 vassal limit, I think it's going to be unplayable on some dates for Easter Roman Emperor even using kingdom vice-royalties and without expanding (i.e. 25-30 vassal limit)

There's a problem with the "Aristocracy vs Plutocracy" law explanation above: vassals of bureaucratic empire are not bureaucratic themselves, so they cannot actually hold cities, only the emperor can. 
I don't think it can be changed without breaking vice-royalties (cf my previous comment).
But feudal vassal tax vs retinue is still an interesting balance, even without cities.

**Comment by loup99** [comment]
> Without the +25 vassal limit, I think it's going to be unplayable on some dates for Eastern Roman Emperor, even using kingdom vice-royalties and without expanding (i.e. 25-30 vassal limit)
I suggest to add a +10 vassal limit too the government form then.

>There's a problem with the "Aristocracy vs Plutocracy" law explanation above: vassals of bureaucratic empire are not bureaucratic themselves, so they cannot actually hold cities, only the emperor can. 
I don't think it can be changed without breaking vice-royalties (cf my previous comment).
But feudal vassal tax vs retinue is still an interesting balance, even without cities.
That is actually something I changed, as the vassals were not intended to have the bureaucratic government form in the main mod, but rather a "Sub-Roman"/"Post-Roman" form that is still to be determined. However, you say that adding that form would restrict vice-royalties? As long as they are landed with a barony, it should work as far as I understand the mechanic.

**Comment by rquinio** [comment]
Ok, it explains, I'll merge the changes.

**Comment by TurtleShroom** [comment]
Is it possible for an empire to reform to the Bureaucracy government type, similar to the "Imperial" law decision?

**Pull request merged**
