### PR TITLE
Imperial Legacy Integration

### PR DESCRIPTION
**Pull request by loup99**
So this is the start of the adaptation of the Imperial Legacy sub-mod made by Arcvalons. Look into the Changelog for the changes. 

If I'm doing this as pull request, it is partially due to having multiple issues and so you can look through the code.

1. There is currently no malus except that those kingdoms can no longer use the Holy War CB

2. There is not yet any decision for the Roman Empire and no CB for the unified empire

3. I can't prevent the usage of one of three separate Imperial Reconquest CB's (WRE, ERE, and sub-roman kingdom) for the others, resulting in all CB's being available for every kingdom (or more) roman realm. 

4. I have no idea of what Localisation Key I need to use in order to have the characters main title disaplayed when the war is declared. For instance "Soissii Reconquest of [Title.GetBaseName]". On the wiki there is a long list, but without any description and I have looked at the others CB's of the mod and vanilla but the "$ORDER$$FIRST_ADJ$" used in those does not work for me.

5. For the laws and governement, the Validator say "invalid node character_modifier in scope GovernementDef" while it works ingame, so I don't know what I should do. There might also be some issues with the law I combined with the governement and I don't really know if the imperial administration and vice-royalties work properly, so it would be appreciated if anyone wants to test that (otherwise I will do it, and I have already done it).

### CODE REVIEW

**Comment by EWattman** [comment]
3. Don't we want it that way? As long as they are only used by Roman Kingdoms and not others, they are used to their intended purpose. I think we did establish that all Roman Kingdoms were sort-of-Usurpers. They can't just be for WRE, ERE and Soissons.

**Comment by loup99** [comment]
The issue here is that everyone can attack in all regions with multiple Cb's

**Comment by EWattman** [comment]
What, that you can declare war on Septem Provinciae multiple times while at war?

**Comment by loup99** [comment]
No, that you can use all of the three CB's freely.

**Comment by loup99** [comment]
OK, so I will try to add this, and then this should be ready to go for now:
1. There is currently no malus except that those kingdoms can no longer use the Holy War CB

2. There is not yet any decision for the Roman Empire and no CB for the unified empire

**Comment by loup99** [comment]
OK, so I will try to add this, and then this should be ready to go for now:
1. There is not yet any decision for the Roman Empire and no CB for the unified empire

One issue remains:
1. As the ERE, for some reason I have a CB available against Soissons.

For the malus, I will let Enlil do the work, he had some nice ideas.

**Comment by loup99** [comment]
The issue fixed itself, and both the malus and the restoration will be done later.

**Pull request merged**
