### PR TITLE
Add a decision to restore the Western Roman Empire

### PR DESCRIPTION
**Pull request by rquinio**
This was a suggested feature on reddit & forum

Other changes:
- Rename namespace imperial_legacy_event to shorter imperial_legacy
- Merge fall_of_rome namespace and file with imperial_legacy (too many namespaces !)

### CODE REVIEW

**Comment by loup99** [comment]
While I like the idea (as well as switching over to bureaucracy from imperial administration), we have to keep in mind how and why the WRE fell. The ERE and religious heads were very much involved, and it makes sense to tie it into it. That is why I held back on implementing this. Also, if we are to add a decision to reform the WRE, it makes sense to do the same for the ERE as well as various other successor states (Charlemagne empire as a dynamic possibility).

Something else I just remembered (memory is short sometimes :stuck_out_tongue:  ) related to  this is that the "reconquest of province" events will need to be adapted with our custom regions, just like vanilla recently did.

**Comment by loup99** [comment]
How do I do to add things to this branch?

**Comment by rquinio** [comment]
I'll resolve the conflict and move this to a branch on the main repo, it'll be easier

**Comment by rquinio** [comment]
So I've created PR https://github.com/loup99/WtWSMS/pull/130 instead, and issue https://github.com/loup99/WtWSMS/issues/129 for the custom regions.

**Pull request closed without merging**
