### PR TITLE
EU4Converter: mapped 2 religions and 3 provinces + mod files update

### PR DESCRIPTION
**Pull request by IhateTrains**

### CODE REVIEW

**Comment by loup99** [comment]
Your PR includes all other changes too.

**Comment by IhateTrains** [comment]
That is intended. Converter branch shouldn't stay behind.

**Comment by IhateTrains** [comment]
Don't merge this PR now, I'm going to do more mapping.

**Comment by IhateTrains** [comment]
I think the converter is polished enough to integrate it into master.

**Comment by loup99** [comment]
So you advice that I merge this and merge with master? Is there anything left to do with it?

**Comment by IhateTrains** [comment]
1. Yes.
2. There are still minor problems like Hypsistarian converting to Samaritan.

**Comment by loup99** [comment]
Okay, but we can live with that for now.

**Pull request merged**
