### PR TITLE
Fork Manifesto

### PR DESCRIPTION
**Pull request by MrZabaglione**
After having been banished, ignored and exiled, the Independent WtWSMS now announces a fork. We demand the return of TurtleShroom, the resignation of Loup and the opening of the WtWSMS Discord to all users.

- Mr. Zabaglione, April 2019

### CODE REVIEW

**Comment by IhateTrains** [comment]
LoL. I have nothing else to say.

**Comment by Abian36** [comment]
Nice try mate, that paranoid map 10/10 would use tin foil on it again

**Comment by loup99** [comment]
First things first. To create a fork of the mod, you need a permission from all developers, and of all the other mods included. If you do not get that, the alternative is to create a sub-mod or just post suggestions through our official channels which are the sub-forum and the Steam Workshop. Furthermore, to use the WtWSMS name, you should also have a permission, because otherwise you claim to speak in the name of those who develop the mod. Needless to say that we will not give permission to any mod which redistributes the whole mod or tries to take the name without crediting us.  By the way, it is not by spreading false information that you will be heard, you have not been "banished, ignored and exiled" from any official channel to my knowledge, and if you have that is not under our responsibility. 

Secondly, with regards to your "demands" one by one. TurtleShroom will not return, he made inacceptable bigoted remarks that made multiple team members feel uncomfortable and ill at ease. Regardless of that, which indicates that he actively hindered development by his abusive behaviour to intimidate developers, we have a zero-tolerance policy towards homophobia, islamophobia and antisemitism, or any other form of hate speech for that matter. TurtleShroom was guilty of all three plus sending personal attacks and insults. He was excluded by unanimity and even refused to apologise for his inacceptable remarks, implying it was the fault of others that he insulted and posted homophobic content. 

Concerning my "resignation", it is a completely absurd suggestion. What would I resign from? I haven't, to my knowledge, been elected to any office or position, I was just invited as a beta tester and ended up becoming a developer to help out. Since I do not exerce any role in particular and thus do not have any responsibility, I can per definition not resign. What I do is to contribute to a mod during my free time because I enjoy it as a hobby. I don't think you would understand either if someone asked you to "resign" from playing football, gardening, photography or whatever you do as a hobby. And no, getting tasks from TurtleShroom to attack me does not count as a hobby. 

Regarding this Discord you speak of, it is completely private and has no official status or relation to the mod. We only have two official channels as I already said, the [sub-forum](https://forum.paradoxplaza.com/forum/index.php?forums/when-the-world-stopped-making-sense-mod.876/) and the [Steam Workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=1247274300). If you have issues with that private Discord, contact those responsible over there, and do not bring it up here because it is completely off-topic. I don't think anyone is interested in those private grudges being posted here, because they do not contribute to development in any way or shape. 

On a last note, this GitHub repository that I host beneath my username is not here to be the instrument of one person wishing to hijack the mod project for his own views. This is a serious project with users that invest their free time into making the mod better, and it has never will be a place for debating personal conflicts or sharing grudges that are completely irrelevant to the mod itself. You can tell TurtleShroom that we are not interested in him and his minions, and that it is not by trying to impose his agenda that he will be reinstated anywhere, this solely confirms what was decided previously, and the no tolerance policy remains. With that said I will close this pull request, and invite you to to not reopen any other.

**Comment by MrZabaglione** [comment]
What about this then? Clearly there is another side of the picture. @Abian36, @IhateTrains and @TurtleShroom can confirm that there is more to this. 

[Presentation1.pdf](https://github.com/loup99/WtWSMS/files/3102524/Presentation1.pdf)

Turtle1
Turtle3
Turtle4

**Comment by IhateTrains** [comment]
You're trying to post the fact that I supported TurtleShroom as a revelation, but  it is known. Regardless, TurtleShroom has lost my support for sharing our private conversation with you without my agreement.

**Comment by loup99** [comment]
There might have been some initial differences in appreciation with regards to whether or not TurtleShroom should be reinstated after his exclusion based upon his behaviour, but we all agreed that his abusive behaviour was inacceptable and that there should be a zero tolerance policy towards insults and any hate speech. As for the rest, IHateTrains answered himself. I'm not interested in reading additional libel directed towards me in an obvious attempt to smear and attack me personally, it does not belong to this repository and to the mod development. If you had anything concrete to suggest for the mod you would go via the official channels, this just shows that you don't have and is only interested in sharing this sort of insulting message.

**Pull request closed without merging**
